# CI, bump package.json version and publish new version to NPM and GitHub

name: Node.js Package

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm ci
      - run: npm test

  bump-version:
    needs: build
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token : ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}
      - run: cat ./package.json
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ''
          token : ${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat ./package.json
        
  publish-npm:
    needs: [build, bump-version]
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git pull
      - run: npm install
      - run: npm ci
      - run: npm run-script build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-gpr:
    needs: [build, bump-version]
    name: "Publish to GitHub"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: '@open-template-hub'
      - run: git pull
      - run: npm install
      - run: npm ci
      - run: npm run-script build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
